name: Build, Test, Lint

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - if: matrix.os == 'windows-latest'
        run: |
          npm install --global --production windows-build-tools@4.0.0
          npm install --global --production node-gyp

      - name: Install & Build
        run: yarn

      - name: Test
        run: yarn test

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint
